runtime: nodejs20

instance_class: F1

automatic_scaling:
  max_instances: 1

entrypoint: "node .next/standalone/server.js"

handlers:
  - url: /_next/static
    static_dir: .next/static

  - url: /(.*\.(gif|png|jpg|txt|svg))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|svg|txt)$

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

env_variables:
  NODE_ENV: "production"
  