name: ex5-バグ報告
description: 不具合に関する報告
title: 【バグ】
labels: ['Type: bug']

body:
  - type: textarea
    attributes:
      label: 現状
      description: 不具合の概要を記入してください。タイトルと重複しても構いません。
      placeholder: 例：ログインしたユーザー名がヘッダーに表示されない。
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ***
        以下項目の記入は任意です。

  - type: textarea
    attributes:
      label: What part(s) of the article would you like to see updated?
      description: |
        - Give as much detail as you can to help us understand the change you want to see. 
        - Why should the docs be changed? What use cases does it support? 
        - What is the expected outcome or behavior?

  - type: textarea
    attributes:
      label: Additional information
      description: |
        - Are you able to reliably reproduce the problem? How often does it occur? How many users are affected?
        - Add any other context or screenshots about the feature here.
