name: c-文書提案
description: 文書の作成・修正に関する提案
title: 【文書】
labels: ['Type: documentation']

body:
  # - type: markdown
  #   attributes:
  #     value: |
  #       ***
  #       #### テンプレートの説明
  #       タイトルは、「◯◯に関するドキュメントを作成する」のように **概要を示して** ください。
  #       気楽にIssueを書きましょう！
  #       ***

  - type: textarea
    attributes:
      label: 提案目的
      value: "- "
    validations:
      required: true

  - type: textarea
    attributes:
      label: 提案詳細
      description: 詳細な提案内容があれば記入してください。
      value: 特になし。

  - type: textarea
    attributes:
      label: その他
      description: |
        関連するIssueや参考資料へのリンクなど何でも記入してください。
        Ctrl+Vやドラッグ&ドロップでスクリーンショットを挿入できます。
      value: 特になし。
